plugins {
    id 'org.springframework.boot' version '4.0.2' apply false

    id 'base'
    id 'jacoco-report-aggregation'
    id 'test-report-aggregation'
}

wrapper {
    gradleVersion = '9.3.1'
}

repositories {
    mavenCentral()
}

// configure test aggregation
dependencies {
    jacocoAggregation project(':mcp-server-fred-app')
    testReportAggregation project(':mcp-server-fred-app')
}

allprojects {
    group = 'ch.alni'
    version = '1.0.0-SNAPSHOT'

    ext {
        buildNumber = System.getenv('CI') ? System.getenv('CI_BUILD_NUMBER') : '0'
        buildVersion = version + '.' + buildNumber
    }
}

reporting {
    reports {
        testCodeCoverageReport(JacocoCoverageReport) {
            testSuiteName = "test"
        }
        testAggregateTestReport(AggregateTestReport) {
            testSuiteName = "test"
        }
    }
}

tasks.check.dependsOn(
        tasks.named('testCodeCoverageReport', JacocoReport), tasks.named('testAggregateTestReport', TestReport)
)
