plugins {
    id 'base'
    id 'jacoco-report-aggregation'
    id 'test-report-aggregation'
}

// configure test aggregation
dependencies {
    jacocoAggregation project(':mcp-server-fred-app')
    testReportAggregation project(':mcp-server-fred-app')
}

group = 'ch.alni'
version = '1.0.0-SNAPSHOT'

allprojects {
    ext {
        buildNumber = System.getenv('CI') ? System.getenv('GITHUB_RUN_NUMBER') : '0'
        buildVersion = buildNumber
    }
}

reporting {
    reports {
        create('testCodeCoverageReport', JacocoCoverageReport) {
            testSuiteName = 'test'
        }

        create('testAggregateTestReport', AggregateTestReport) {
            testSuiteName = 'test'
        }
    }
}

tasks.named('check') {
    dependsOn(
            tasks.named('testCodeCoverageReport', JacocoReport),
            tasks.named('testAggregateTestReport', TestReport)
    )
}
