import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        gradlePluginPortal()
    }

    plugins {
        id 'org.springframework.boot' version '4.1.0'
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS

    repositories {
        mavenCentral()
    }
}

rootProject.name = 'mcp-server-fred'

includeBuild('mcp-server-conventions') {
    name = 'mcp-server-conventions'
}

include 'mcp-server-platform',
        'mcp-server-fred-app',
        'mcp-server-edgar'
