pluginManagement {
    repositories {
        gradlePluginPortal()
    }

    plugins {
        id 'org.springframework.boot' version '4.0.5'
    }
}

rootProject.name = 'mcp-server-fred'

includeBuild('mcp-server-conventions') {
    name = 'mcp-server-conventions'
}

include 'mcp-server-platform',
        'mcp-server-fred-app',
        'mcp-server-edgar'
