plugins {
    id 'java'
    id 'jacoco'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    // somehow this is needed by Spring Boot 3 to ensure
    // that the properties can be used as parameters to other properties
    options.compilerArgs += ['-parameters']
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.named('test', Test) {
    // for every local test run the test coverage report
    finalizedBy(tasks.named('jacocoTestReport'))
}

dependencies {
    implementation platform(project(':mcp-server-platform'))
    annotationProcessor platform(project(':mcp-server-platform'))
    testAnnotationProcessor platform(project(':mcp-server-platform'))

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'

    testCompileOnly 'org.slf4j:slf4j-api'
    testRuntimeOnly 'ch.qos.logback:logback-classic'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
