import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java-platform'
    id 'idea'
}

javaPlatform {
    allowDependencies()
}

dependencies {
    constraints {
        api 'org.jetbrains:annotations:24.0.1'

        api(group: 'com.google.guava', name: 'guava', version: '31.0.1-jre')
        api('io.swagger.core.v3:swagger-annotations-jakarta:2.2.9')

        api('org.projectlombok:lombok:1.18.32')
    }

    api platform(SpringBootPlugin.BOM_COORDINATES)
    api platform('org.springframework.ai:spring-ai-bom:1.1.2')
    api platform('com.squareup.okhttp3:okhttp-bom:5.2.0')
}
