spring:
  ai:
    mcp:
      server:
        name: mcp-server-fred
        # building the server addressed over Streamable HTTP
        protocol: streamable
        type: async

  # disconnect after 10 seconds to play nicely with Kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 10s

fred:
  http:
    base-url: https://api.stlouisfed.org/
    read-timeout: 30s
    connect-timeout: 30s
