plugins {
    id 'java'
    id 'jacoco'
}

repositories {
    mavenCentral()

    flatDir {
        dirs "${rootDir}/lib"
    }
}

java {
    targetCompatibility = JavaVersion.VERSION_21
    sourceCompatibility = JavaVersion.VERSION_21
}

compileJava {
    // somehow this is needed by Spring Boot 3 to ensure
    // that the properties can be used as parameters to other properties
    options.compilerArgs += ['-parameters']
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    finalizedBy tasks.jacocoTestReport
}

dependencies {
    implementation platform(project(':trading-machine-platform'))
    compileOnly platform(project(':trading-machine-platform'))
    annotationProcessor platform(project(':trading-machine-platform'))

    testImplementation platform(project(':trading-machine-platform'))
    testCompileOnly platform(project(':trading-machine-platform'))
    testAnnotationProcessor platform(project(':trading-machine-platform'))

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'

    testCompileOnly 'org.slf4j:slf4j-api'
    testRuntimeOnly 'ch.qos.logback:logback-classic'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
